version: '3.8'

services:
  appserver:
    build:
      context: .
      dockerfile: docker-compose-files/appserver/Dockerfile
    container_name: appserver
    working_dir: /var/www/docroot
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/
      - ./docker-compose-files/appserver/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker-compose-files/appserver/php.ini:/usr/local/etc/php/php.ini
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    depends_on:
      - database
    networks:
      - backend

  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - db-data:/var/lib/mysql
      - ./:/var/www/
    networks:
      - backend

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ./etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - backend

  minio:
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./minio-data:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - backend
    ports:
      - "9000:9000"

  milvus:
    image: milvusdb/milvus:v2.4.8
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - ./milvus-data:/var/lib/milvus/db
    depends_on:
      - etcd
      - minio
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
    driver: local
